development:
  adapter: postgresql
  database: hytir_development
  host: localhost
  username: postgres
  password: password
test:
  adapter: postgresql
  database: hytir_test
  host: localhost
  username: postgres
  password: password
production:
  adapter: postgresql
  database: hytir
  host: localhost
