development:
  adapter: postgresql
  database: hytir_development
  host: localhost
  username: postgres
  password: password
test:
  adapter: postgresql
  database: hytir_test
  host: localhost
  username: postgres
  password: password
production:
  databse: darlpqj5vpv8jh
  host: ec2-107-20-217-22.compute-1.amazonaws.com
  user: mfctlsyogrgdkq
  password: t4iR4ooe7ewohsHf2XlX6QtOjm
